services:
  merlin:
    image: ghcr.io/joachimgoris/merlin:latest
    container_name: merlin
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /var/run/docker.sock:/var/run/podman/podman.sock
      - merlin-data:/app/data
    environment:
      - HOST_ROOT_PATH=/host/root
    restart: unless-stopped

volumes:
  merlin-data:
