services:
  merlin:
    build: .
    container_name: merlin
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/podman/podman.sock:/var/run/podman/podman.sock
      - merlin-data:/app/data
    environment:
      - HOST_ROOT_PATH=/host/root
    restart: unless-stopped
    security_opt:
      - label=disable

volumes:
  merlin-data:
