services:
  merlin:
    build: .
    container_name: merlin
    ports:
      - "5050:5050"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/podman/podman.sock:/var/run/podman/podman.sock
    environment:
      - HOST_ROOT_PATH=/host/root
    restart: unless-stopped
    security_opt:
      - label=disable
